"""Provider-independent persistence, identity, object, and worker contracts."""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import BinaryIO, Protocol, Self
from uuid import UUID

from .models import (
    Actor,
    Artifact,
    AuditEvent,
    AuthenticatedIdentity,
    BrowserSession,
    CommandRecord,
    DownloadDescriptor,
    ExternalIdentity,
    LegacyRegistration,
    ObjectDescriptor,
    OidcTransaction,
    Organization,
    OrganizationMembership,
    OutboxEvent,
    Paper,
    PaperVersion,
    Project,
    ProjectMembership,
    ReviewEvent,
    ReviewJob,
    StageInputManifest,
    StageOutputSpec,
    TemporaryObjectDescriptor,
    TenantScope,
    User,
    WorkItem,
)


class UserRepository(Protocol):
    def get(self, user_id: UUID) -> User | None: ...
    def get_identity(self, issuer: str, subject: str) -> ExternalIdentity | None: ...
    def get_identity_by_id(self, identity_id: UUID) -> ExternalIdentity | None: ...
    def add(self, user: User) -> None: ...
    def add_identity(self, identity: ExternalIdentity) -> None: ...
    def save_identity(self, identity: ExternalIdentity, expected_version: int) -> None: ...
    def unlink_identity(
        self,
        identity: ExternalIdentity,
        expected_version: int,
        unlinked_at: datetime,
    ) -> ExternalIdentity: ...


class OrganizationRepository(Protocol):
    def get(self, scope: TenantScope) -> Organization | None: ...
    def list_for_user(self, user_id: UUID) -> Iterable[OrganizationMembership]: ...
    def list_memberships(self, scope: TenantScope) -> Iterable[OrganizationMembership]: ...
    def add(self, scope: TenantScope, organization: Organization) -> None: ...
    def get_membership(self, scope: TenantScope, user_id: UUID) -> OrganizationMembership | None: ...
    def get_membership_by_id(
        self, scope: TenantScope, membership_id: UUID
    ) -> OrganizationMembership | None: ...
    def save_membership(
        self,
        scope: TenantScope,
        membership: OrganizationMembership,
        expected_version: int | None,
    ) -> None: ...


class ProjectRepository(Protocol):
    def get(self, scope: TenantScope) -> Project | None: ...
    def list(self, scope: TenantScope) -> Iterable[Project]: ...
    def list_for_organization(self, scope: TenantScope) -> Iterable[Project]: ...
    def list_for_user(self, user_id: UUID) -> Iterable[ProjectMembership]: ...
    def list_memberships(self, scope: TenantScope) -> Iterable[ProjectMembership]: ...
    def add(self, scope: TenantScope, project: Project) -> None: ...
    def save(self, scope: TenantScope, project: Project, expected_version: int) -> None: ...
    def get_membership(self, scope: TenantScope, user_id: UUID) -> ProjectMembership | None: ...
    def get_membership_by_id(
        self, scope: TenantScope, membership_id: UUID
    ) -> ProjectMembership | None: ...
    def save_membership(self, scope: TenantScope, membership: ProjectMembership, expected_version: int | None) -> None: ...


class PaperRepository(Protocol):
    def get(self, scope: TenantScope, paper_id: UUID) -> Paper | None: ...
    def find_by_content_digest(self, scope: TenantScope, sha256: str) -> Paper | None: ...
    def get_version(self, scope: TenantScope, version_id: UUID) -> PaperVersion | None: ...
    def list(self, scope: TenantScope) -> Iterable[Paper]: ...
    def add(self, scope: TenantScope, paper: Paper, version: PaperVersion) -> None: ...
    def add_version(self, scope: TenantScope, version: PaperVersion, expected_paper_version: int) -> None: ...


class ReviewJobRepository(Protocol):
    def get(self, scope: TenantScope, job_id: UUID) -> ReviewJob | None: ...
    def list(self, scope: TenantScope) -> Iterable[ReviewJob]: ...
    def add(self, scope: TenantScope, job: ReviewJob) -> None: ...
    def save(self, scope: TenantScope, job: ReviewJob, expected_version: int) -> None: ...
    def append_event(self, scope: TenantScope, event: ReviewEvent) -> None: ...
    def list_events(self, scope: TenantScope, job_id: UUID) -> tuple[ReviewEvent, ...]: ...


class ArtifactRepository(Protocol):
    def get(self, scope: TenantScope, artifact_id: UUID) -> Artifact | None: ...
    def list_for_job(self, scope: TenantScope, job_id: UUID) -> Iterable[Artifact]: ...
    def add(self, scope: TenantScope, artifact: Artifact) -> None: ...


class CommandRepository(Protocol):
    def get(
        self,
        scope: TenantScope,
        actor_id: UUID,
        operation: str,
        idempotency_key: str,
    ) -> CommandRecord | None: ...

    def reserve(self, scope: TenantScope, command: CommandRecord) -> None: ...
    def reserve_or_replay(self, scope: TenantScope, command: CommandRecord) -> CommandRecord: ...
    def complete(self, scope: TenantScope, command: CommandRecord) -> None: ...


class WorkItemRepository(Protocol):
    def enqueue(self, scope: TenantScope, item: WorkItem) -> None: ...
    def get(self, scope: TenantScope, item_id: UUID) -> WorkItem | None: ...
    def claim(self, scope: TenantScope, worker_id: str, lease_seconds: int) -> WorkItem | None: ...
    def renew(
        self,
        scope: TenantScope,
        item_id: UUID,
        lease_owner: str,
        lease_seconds: int,
    ) -> WorkItem: ...
    def complete(self, scope: TenantScope, item_id: UUID, lease_owner: str) -> None: ...
    def fail(self, scope: TenantScope, item: WorkItem, lease_owner: str) -> None: ...


class OutboxRepository(Protocol):
    def append(self, scope: TenantScope, event: OutboxEvent) -> None: ...
    def claim_batch(self, scope: TenantScope, limit: int) -> tuple[OutboxEvent, ...]: ...
    def mark_published(self, scope: TenantScope, event_id: UUID) -> None: ...


class AuditRepository(Protocol):
    def append(self, scope: TenantScope, event: AuditEvent) -> None: ...
    def list(self, scope: TenantScope) -> Iterable[AuditEvent]: ...
    def list_for_organization(self, scope: TenantScope) -> Iterable[AuditEvent]: ...


class LegacyRegistrationRepository(Protocol):
    def get(self, scope: TenantScope, registration_id: UUID) -> LegacyRegistration | None: ...
    def add(self, scope: TenantScope, registration: LegacyRegistration) -> None: ...


class BrowserSessionRepository(Protocol):
    def get_by_digest(self, session_digest: str) -> BrowserSession | None: ...
    def save(self, session: BrowserSession) -> None: ...
    def revoke_for_user(self, user_id: UUID) -> None: ...


class OidcTransactionRepository(Protocol):
    def get_for_update(self, transaction_id: UUID) -> OidcTransaction | None: ...
    def add(self, transaction: OidcTransaction) -> None: ...
    def consume(self, transaction: OidcTransaction) -> None: ...
    def delete(self, transaction_id: UUID) -> None: ...


class IdentityProvider(Protocol):
    def validate_bearer(self, bearer: str) -> AuthenticatedIdentity: ...
    def build_authorization_url(self, transaction_id: UUID) -> str: ...
    def exchange_callback(self, transaction_id: UUID, authorization_code: str) -> AuthenticatedIdentity: ...


class ObjectStore(Protocol):
    def create_temporary(self, scope: TenantScope, maximum_size_bytes: int) -> UUID: ...
    def write_temporary(self, scope: TenantScope, upload_id: UUID, source: BinaryIO) -> TemporaryObjectDescriptor: ...
    def publish(self, scope: TenantScope, temporary: TemporaryObjectDescriptor, object_id: str) -> ObjectDescriptor: ...
    def metadata(self, scope: TenantScope, object_id: str) -> ObjectDescriptor | None: ...
    def open_immutable(self, scope: TenantScope, object_id: str) -> BinaryIO: ...
    def download_descriptor(self, scope: TenantScope, object_id: str, filename: str) -> DownloadDescriptor: ...
    def tombstone(self, scope: TenantScope, object_id: str) -> None: ...
    def delete_temporary(self, scope: TenantScope, upload_id: UUID) -> None: ...


class WorkspaceMaterializer(Protocol):
    def materialize(
        self,
        scope: TenantScope,
        job: ReviewJob,
        stage: str,
        input_manifest: StageInputManifest,
        destination: Path,
    ) -> Path: ...


class StageArtifactPublisher(Protocol):
    def publish(
        self,
        scope: TenantScope,
        job: ReviewJob,
        stage: str,
        output_spec: StageOutputSpec,
        workspace: Path,
    ) -> tuple[ObjectDescriptor, ...]: ...


class LegacyReader(Protocol):
    def read_job(self, scope: TenantScope, registration: LegacyRegistration) -> ReviewJob: ...
    def read_artifact(
        self,
        scope: TenantScope,
        registration: LegacyRegistration,
        logical_name: str,
    ) -> BinaryIO: ...


class EventDispatcher(Protocol):
    def dispatch(self, events: tuple[OutboxEvent, ...]) -> None: ...


class UnitOfWork(Protocol):
    """One application transaction; provider sessions remain adapter-private."""

    users: UserRepository
    organizations: OrganizationRepository
    projects: ProjectRepository
    papers: PaperRepository
    review_jobs: ReviewJobRepository
    artifacts: ArtifactRepository
    commands: CommandRepository
    work_items: WorkItemRepository
    outbox: OutboxRepository
    audit: AuditRepository
    legacy_registrations: LegacyRegistrationRepository
    browser_sessions: BrowserSessionRepository
    oidc_transactions: OidcTransactionRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self, actor: Actor) -> UnitOfWork: ...
