"""Immutable PostgreSQL 16 catalog signature for schema revision 0001."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from types import MappingProxyType
from typing import Any

_SIGNATURE_KEYS = ("tables", "columns", "constraints", "indexes", "triggers")

CATALOG_INSPECTION_SQL = "WITH timeout_setting AS (\n    SELECT set_config('statement_timeout', '2000', true)\n), owned_tables AS (\n    SELECT unnest(CAST(:owned_tables AS text[])) AS table_name\n)\nSELECT\n    (SELECT version_num FROM alembic_version LIMIT 1) AS alembic_revision,\n    (SELECT value FROM schema_metadata WHERE key = 'platform_revision') AS schema_revision,\n    (SELECT value FROM schema_metadata WHERE key = 'platform_catalog_fingerprint') AS stored_fingerprint,\n    ARRAY(\n        SELECT format('%s|%s|%s', relations.relname, relations.relkind, relations.relpersistence)\n        FROM pg_class AS relations\n        JOIN pg_namespace AS namespaces ON namespaces.oid = relations.relnamespace\n        JOIN owned_tables ON owned_tables.table_name = relations.relname\n        WHERE namespaces.nspname = current_schema() AND relations.relkind IN ('r', 'p')\n        ORDER BY relations.relname\n    ) AS tables,\n    ARRAY(\n        SELECT format(\n            '%s|%s|%s|%s|%s|%s|%s|%s',\n            relations.relname,\n            attributes.attnum,\n            attributes.attname,\n            format_type(attributes.atttypid, attributes.atttypmod),\n            attributes.attnotnull,\n            COALESCE(pg_get_expr(defaults.adbin, defaults.adrelid, true), ''),\n            attributes.attidentity,\n            attributes.attgenerated\n        )\n        FROM pg_attribute AS attributes\n        JOIN pg_class AS relations ON relations.oid = attributes.attrelid\n        JOIN pg_namespace AS namespaces ON namespaces.oid = relations.relnamespace\n        JOIN owned_tables ON owned_tables.table_name = relations.relname\n        LEFT JOIN pg_attrdef AS defaults\n            ON defaults.adrelid = attributes.attrelid AND defaults.adnum = attributes.attnum\n        WHERE namespaces.nspname = current_schema()\n            AND attributes.attnum > 0\n            AND NOT attributes.attisdropped\n        ORDER BY relations.relname, attributes.attnum\n    ) AS columns,\n    ARRAY(\n        SELECT format(\n            '%s|%s|%s|%s',\n            relations.relname,\n            constraints.conname,\n            constraints.contype,\n            pg_get_constraintdef(constraints.oid, true)\n        )\n        FROM pg_constraint AS constraints\n        JOIN pg_class AS relations ON relations.oid = constraints.conrelid\n        JOIN pg_namespace AS namespaces ON namespaces.oid = relations.relnamespace\n        JOIN owned_tables ON owned_tables.table_name = relations.relname\n        WHERE namespaces.nspname = current_schema()\n        ORDER BY relations.relname, constraints.conname\n    ) AS constraints,\n    ARRAY(\n        SELECT format(\n            '%s|%s|%s',\n            relations.relname,\n            index_relations.relname,\n            pg_get_indexdef(indexes.indexrelid, 0, true)\n        )\n        FROM pg_index AS indexes\n        JOIN pg_class AS relations ON relations.oid = indexes.indrelid\n        JOIN pg_class AS index_relations ON index_relations.oid = indexes.indexrelid\n        JOIN pg_namespace AS namespaces ON namespaces.oid = relations.relnamespace\n        JOIN owned_tables ON owned_tables.table_name = relations.relname\n        WHERE namespaces.nspname = current_schema()\n        ORDER BY relations.relname, index_relations.relname\n    ) AS indexes,\n    ARRAY(\n        SELECT format(\n            '%s|%s|%s',\n            relations.relname,\n            triggers.tgname,\n            pg_get_triggerdef(triggers.oid, true)\n        )\n        FROM pg_trigger AS triggers\n        JOIN pg_class AS relations ON relations.oid = triggers.tgrelid\n        JOIN pg_namespace AS namespaces ON namespaces.oid = relations.relnamespace\n        JOIN owned_tables ON owned_tables.table_name = relations.relname\n        WHERE namespaces.nspname = current_schema() AND NOT triggers.tgisinternal\n        ORDER BY relations.relname, triggers.tgname\n    ) AS triggers\nFROM timeout_setting"

EXPECTED_CATALOG_SIGNATURE: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "tables": tuple([
    "artifacts|r|p",
    "audit_events|r|p",
    "browser_sessions|r|p",
    "commands|r|p",
    "external_identities|r|p",
    "legacy_registrations|r|p",
    "oidc_transactions|r|p",
    "organization_memberships|r|p",
    "organizations|r|p",
    "outbox_events|r|p",
    "paper_versions|r|p",
    "papers|r|p",
    "project_memberships|r|p",
    "projects|r|p",
    "report_versions|r|p",
    "review_attempts|r|p",
    "review_events|r|p",
    "review_jobs|r|p",
    "schema_metadata|r|p",
    "stage_manifests|r|p",
    "users|r|p",
    "work_items|r|p"
]),
        "columns": tuple([
    "artifacts|1|id|uuid|t|||",
    "artifacts|2|organization_id|uuid|t|||",
    "artifacts|3|project_id|uuid|t|||",
    "artifacts|4|job_id|uuid|t|||",
    "artifacts|5|stage_manifest_id|uuid|f|||",
    "artifacts|6|report_version_id|uuid|f|||",
    "artifacts|7|logical_name|character varying(255)|t|||",
    "artifacts|8|object_id|text|t|||",
    "artifacts|9|media_type|character varying(255)|t|||",
    "artifacts|10|size_bytes|bigint|t|||",
    "artifacts|11|sha256|character varying(64)|t|||",
    "artifacts|12|schema_version|integer|t|||",
    "artifacts|13|status|character varying(32)|t|||",
    "artifacts|14|created_at|timestamp with time zone|t|||",
    "artifacts|15|tombstoned_at|timestamp with time zone|f|||",
    "audit_events|1|id|uuid|t|||",
    "audit_events|2|actor_id|uuid|t|||",
    "audit_events|3|actor_kind|character varying(32)|t|||",
    "audit_events|4|identity_id|uuid|f|||",
    "audit_events|5|organization_id|uuid|f|||",
    "audit_events|6|project_id|uuid|f|||",
    "audit_events|7|scope_project_id|uuid|t|COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid)||s",
    "audit_events|8|command_id|uuid|f|||",
    "audit_events|9|action|character varying(128)|t|||",
    "audit_events|10|resource_type|character varying(128)|t|||",
    "audit_events|11|resource_id|character varying(255)|t|||",
    "audit_events|12|outcome|character varying(32)|t|||",
    "audit_events|13|request_id|character varying(255)|t|||",
    "audit_events|14|metadata|jsonb|t|||",
    "audit_events|15|created_at|timestamp with time zone|t|||",
    "browser_sessions|1|id|uuid|t|||",
    "browser_sessions|2|user_id|uuid|t|||",
    "browser_sessions|3|identity_id|uuid|t|||",
    "browser_sessions|4|session_digest|character varying(64)|t|||",
    "browser_sessions|5|csrf_digest|character varying(64)|t|||",
    "browser_sessions|6|provider_credential_ref|text|t|||",
    "browser_sessions|7|token_expires_at|timestamp with time zone|t|||",
    "browser_sessions|8|expires_at|timestamp with time zone|t|||",
    "browser_sessions|9|idle_expires_at|timestamp with time zone|t|||",
    "browser_sessions|10|created_at|timestamp with time zone|t|||",
    "browser_sessions|11|updated_at|timestamp with time zone|t|||",
    "browser_sessions|12|revoked_at|timestamp with time zone|f|||",
    "commands|1|id|uuid|t|||",
    "commands|2|organization_id|uuid|t|||",
    "commands|3|project_id|uuid|f|||",
    "commands|4|scope_project_id|uuid|t|COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid)||s",
    "commands|5|actor_id|uuid|t|||",
    "commands|6|operation|character varying(128)|t|||",
    "commands|7|idempotency_key|character varying(255)|t|||",
    "commands|8|payload_digest|character varying(64)|t|||",
    "commands|9|response_status|integer|f|||",
    "commands|10|response_body|jsonb|f|||",
    "commands|11|created_at|timestamp with time zone|t|||",
    "commands|12|completed_at|timestamp with time zone|f|||",
    "external_identities|1|id|uuid|t|||",
    "external_identities|2|user_id|uuid|t|||",
    "external_identities|3|issuer|character varying(2048)|t|||",
    "external_identities|4|subject|character varying(512)|t|||",
    "external_identities|5|verified_claims|jsonb|t|||",
    "external_identities|6|last_seen_at|timestamp with time zone|t|||",
    "external_identities|7|created_at|timestamp with time zone|t|||",
    "external_identities|8|disabled_at|timestamp with time zone|f|||",
    "external_identities|9|version|integer|t|||",
    "legacy_registrations|1|id|uuid|t|||",
    "legacy_registrations|2|organization_id|uuid|t|||",
    "legacy_registrations|3|project_id|uuid|t|||",
    "legacy_registrations|4|legacy_type|character varying(64)|t|||",
    "legacy_registrations|5|opaque_locator|text|t|||",
    "legacy_registrations|6|manifest_digest|character varying(64)|t|||",
    "legacy_registrations|7|schema_version|integer|t|||",
    "legacy_registrations|8|status|character varying(32)|t|||",
    "legacy_registrations|9|registered_by|uuid|t|||",
    "legacy_registrations|10|created_at|timestamp with time zone|t|||",
    "legacy_registrations|11|updated_at|timestamp with time zone|t|||",
    "oidc_transactions|1|id|uuid|t|||",
    "oidc_transactions|2|state_digest|character varying(64)|t|||",
    "oidc_transactions|3|nonce_digest|character varying(64)|t|||",
    "oidc_transactions|4|encrypted_pkce_verifier|bytea|t|||",
    "oidc_transactions|5|encryption_key_id|character varying(64)|t|||",
    "oidc_transactions|6|return_path|text|t|||",
    "oidc_transactions|7|expires_at|timestamp with time zone|t|||",
    "oidc_transactions|8|created_at|timestamp with time zone|t|||",
    "oidc_transactions|9|consumed_at|timestamp with time zone|f|||",
    "organization_memberships|1|id|uuid|t|||",
    "organization_memberships|2|organization_id|uuid|t|||",
    "organization_memberships|3|user_id|uuid|t|||",
    "organization_memberships|4|role|character varying(32)|t|||",
    "organization_memberships|5|status|character varying(32)|t|||",
    "organization_memberships|6|version|integer|t|||",
    "organization_memberships|7|created_at|timestamp with time zone|t|||",
    "organization_memberships|8|updated_at|timestamp with time zone|t|||",
    "organization_memberships|9|revoked_at|timestamp with time zone|f|||",
    "organizations|1|id|uuid|t|||",
    "organizations|2|slug|character varying(100)|t|||",
    "organizations|3|name|character varying(255)|t|||",
    "organizations|4|status|character varying(32)|t|||",
    "organizations|5|version|integer|t|||",
    "organizations|6|created_at|timestamp with time zone|t|||",
    "organizations|7|updated_at|timestamp with time zone|t|||",
    "outbox_events|1|id|uuid|t|||",
    "outbox_events|2|organization_id|uuid|t|||",
    "outbox_events|3|project_id|uuid|f|||",
    "outbox_events|4|aggregate_type|character varying(128)|t|||",
    "outbox_events|5|aggregate_id|uuid|t|||",
    "outbox_events|6|aggregate_sequence|bigint|t|||",
    "outbox_events|7|event_type|character varying(128)|t|||",
    "outbox_events|8|schema_version|integer|t|||",
    "outbox_events|9|payload|jsonb|t|||",
    "outbox_events|10|publication_attempts|integer|t|||",
    "outbox_events|11|published_at|timestamp with time zone|f|||",
    "outbox_events|12|created_at|timestamp with time zone|t|||",
    "paper_versions|1|id|uuid|t|||",
    "paper_versions|2|organization_id|uuid|t|||",
    "paper_versions|3|project_id|uuid|t|||",
    "paper_versions|4|paper_id|uuid|t|||",
    "paper_versions|5|source_object_id|text|t|||",
    "paper_versions|6|filename|text|t|||",
    "paper_versions|7|media_type|character varying(255)|t|||",
    "paper_versions|8|size_bytes|bigint|t|||",
    "paper_versions|9|sha256|character varying(64)|t|||",
    "paper_versions|10|created_by|uuid|t|||",
    "paper_versions|11|revision|integer|t|||",
    "paper_versions|12|created_at|timestamp with time zone|t|||",
    "papers|1|id|uuid|t|||",
    "papers|2|organization_id|uuid|t|||",
    "papers|3|project_id|uuid|t|||",
    "papers|4|content_sha256|character varying(64)|t|||",
    "papers|5|current_version_id|uuid|f|||",
    "papers|6|status|character varying(32)|t|||",
    "papers|7|version|integer|t|||",
    "papers|8|created_at|timestamp with time zone|t|||",
    "papers|9|updated_at|timestamp with time zone|t|||",
    "project_memberships|1|id|uuid|t|||",
    "project_memberships|2|organization_id|uuid|t|||",
    "project_memberships|3|project_id|uuid|t|||",
    "project_memberships|4|user_id|uuid|t|||",
    "project_memberships|5|role|character varying(32)|t|||",
    "project_memberships|6|status|character varying(32)|t|||",
    "project_memberships|7|version|integer|t|||",
    "project_memberships|8|created_at|timestamp with time zone|t|||",
    "project_memberships|9|updated_at|timestamp with time zone|t|||",
    "project_memberships|10|revoked_at|timestamp with time zone|f|||",
    "projects|1|id|uuid|t|||",
    "projects|2|organization_id|uuid|t|||",
    "projects|3|name|character varying(255)|t|||",
    "projects|4|status|character varying(32)|t|||",
    "projects|5|version|integer|t|||",
    "projects|6|created_at|timestamp with time zone|t|||",
    "projects|7|updated_at|timestamp with time zone|t|||",
    "report_versions|1|id|uuid|t|||",
    "report_versions|2|organization_id|uuid|t|||",
    "report_versions|3|project_id|uuid|t|||",
    "report_versions|4|job_id|uuid|t|||",
    "report_versions|5|revision|integer|t|||",
    "report_versions|6|schema_version|integer|t|||",
    "report_versions|7|content_sha256|character varying(64)|t|||",
    "report_versions|8|status|character varying(32)|t|||",
    "report_versions|9|created_by|uuid|t|||",
    "report_versions|10|created_at|timestamp with time zone|t|||",
    "report_versions|11|published_at|timestamp with time zone|f|||",
    "report_versions|12|superseded_at|timestamp with time zone|f|||",
    "review_attempts|1|id|uuid|t|||",
    "review_attempts|2|organization_id|uuid|t|||",
    "review_attempts|3|project_id|uuid|t|||",
    "review_attempts|4|job_id|uuid|t|||",
    "review_attempts|5|attempt_number|integer|t|||",
    "review_attempts|6|status|character varying(32)|t|||",
    "review_attempts|7|started_at|timestamp with time zone|f|||",
    "review_attempts|8|finished_at|timestamp with time zone|f|||",
    "review_attempts|9|created_at|timestamp with time zone|t|||",
    "review_events|1|id|uuid|t|||",
    "review_events|2|organization_id|uuid|t|||",
    "review_events|3|project_id|uuid|t|||",
    "review_events|4|job_id|uuid|t|||",
    "review_events|5|aggregate_sequence|bigint|t|||",
    "review_events|6|event_type|character varying(128)|t|||",
    "review_events|7|schema_version|integer|t|||",
    "review_events|8|payload|jsonb|t|||",
    "review_events|9|created_at|timestamp with time zone|t|||",
    "review_jobs|1|id|uuid|t|||",
    "review_jobs|2|organization_id|uuid|t|||",
    "review_jobs|3|project_id|uuid|t|||",
    "review_jobs|4|paper_version_id|uuid|t|||",
    "review_jobs|5|mode|character varying(32)|t|||",
    "review_jobs|6|stage|character varying(64)|t|||",
    "review_jobs|7|status|character varying(32)|t|||",
    "review_jobs|8|version|integer|t|||",
    "review_jobs|9|attempt|integer|t|||",
    "review_jobs|10|created_by|uuid|t|||",
    "review_jobs|11|created_at|timestamp with time zone|t|||",
    "review_jobs|12|updated_at|timestamp with time zone|t|||",
    "review_jobs|13|cancelled_at|timestamp with time zone|f|||",
    "review_jobs|14|safe_error_code|character varying(128)|f|||",
    "schema_metadata|1|key|character varying(100)|t|||",
    "schema_metadata|2|value|character varying(255)|t|||",
    "schema_metadata|3|updated_at|timestamp with time zone|t|||",
    "stage_manifests|1|id|uuid|t|||",
    "stage_manifests|2|organization_id|uuid|t|||",
    "stage_manifests|3|project_id|uuid|t|||",
    "stage_manifests|4|job_id|uuid|t|||",
    "stage_manifests|5|attempt_id|uuid|t|||",
    "stage_manifests|6|stage|character varying(64)|t|||",
    "stage_manifests|7|input_revision|integer|t|||",
    "stage_manifests|8|output_revision|integer|t|||",
    "stage_manifests|9|schema_version|integer|t|||",
    "stage_manifests|10|manifest|jsonb|t|||",
    "stage_manifests|11|status|character varying(32)|t|||",
    "stage_manifests|12|created_at|timestamp with time zone|t|||",
    "stage_manifests|13|committed_at|timestamp with time zone|f|||",
    "users|1|id|uuid|t|||",
    "users|2|status|character varying(32)|t|||",
    "users|3|display_name|character varying(255)|t|||",
    "users|4|version|integer|t|||",
    "users|5|created_at|timestamp with time zone|t|||",
    "users|6|updated_at|timestamp with time zone|t|||",
    "work_items|1|id|uuid|t|||",
    "work_items|2|organization_id|uuid|t|||",
    "work_items|3|project_id|uuid|t|||",
    "work_items|4|job_id|uuid|t|||",
    "work_items|5|attempt_id|uuid|t|||",
    "work_items|6|stage|character varying(64)|t|||",
    "work_items|7|input_revision|integer|t|||",
    "work_items|8|attempt_count|integer|t|||",
    "work_items|9|max_attempts|integer|t|||",
    "work_items|10|available_at|timestamp with time zone|t|||",
    "work_items|11|lease_owner|character varying(255)|f|||",
    "work_items|12|lease_expires_at|timestamp with time zone|f|||",
    "work_items|13|dead_lettered_at|timestamp with time zone|f|||",
    "work_items|14|safe_error_code|character varying(128)|f|||",
    "work_items|15|created_at|timestamp with time zone|t|||",
    "work_items|16|updated_at|timestamp with time zone|t|||"
]),
        "constraints": tuple([
    "artifacts|ck_artifacts_schema_version_positive|c|CHECK (schema_version > 0)",
    "artifacts|ck_artifacts_sha256|c|CHECK (char_length(sha256::text) = 64)",
    "artifacts|ck_artifacts_size_nonnegative|c|CHECK (size_bytes >= 0)",
    "artifacts|ck_artifacts_status|c|CHECK (status::text = ANY (ARRAY['available'::character varying, 'tombstoned'::character varying]::text[]))",
    "artifacts|fk_artifacts_job_tenant|f|FOREIGN KEY (organization_id, project_id, job_id) REFERENCES review_jobs(organization_id, project_id, id)",
    "artifacts|fk_artifacts_report_version_tenant|f|FOREIGN KEY (organization_id, project_id, job_id, report_version_id) REFERENCES report_versions(organization_id, project_id, job_id, id)",
    "artifacts|fk_artifacts_stage_manifest_tenant|f|FOREIGN KEY (organization_id, project_id, job_id, stage_manifest_id) REFERENCES stage_manifests(organization_id, project_id, job_id, id)",
    "artifacts|pk_artifacts|p|PRIMARY KEY (id)",
    "artifacts|uq_artifacts_job_logical_name|u|UNIQUE (job_id, logical_name)",
    "artifacts|uq_artifacts_object_id|u|UNIQUE (object_id)",
    "audit_events|ck_audit_events_actor_kind|c|CHECK (actor_kind::text = ANY (ARRAY['user'::character varying, 'operator'::character varying, 'service'::character varying]::text[]))",
    "audit_events|ck_audit_events_command_organization_required|c|CHECK (command_id IS NULL OR organization_id IS NOT NULL)",
    "audit_events|ck_audit_events_outcome|c|CHECK (outcome::text = ANY (ARRAY['succeeded'::character varying, 'denied'::character varying, 'failed'::character varying]::text[]))",
    "audit_events|ck_audit_events_project_not_scope_sentinel|c|CHECK (project_id IS NULL OR project_id <> '00000000-0000-0000-0000-000000000000'::uuid)",
    "audit_events|fk_audit_events_command_organization|f|FOREIGN KEY (organization_id, command_id) REFERENCES commands(organization_id, id)",
    "audit_events|fk_audit_events_command_project|f|FOREIGN KEY (organization_id, project_id, command_id) REFERENCES commands(organization_id, project_id, id)",
    "audit_events|fk_audit_events_command_scope|f|FOREIGN KEY (organization_id, scope_project_id, command_id) REFERENCES commands(organization_id, scope_project_id, id)",
    "audit_events|fk_audit_events_identity|f|FOREIGN KEY (identity_id) REFERENCES external_identities(id)",
    "audit_events|fk_audit_events_organization|f|FOREIGN KEY (organization_id) REFERENCES organizations(id)",
    "audit_events|fk_audit_events_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "audit_events|pk_audit_events|p|PRIMARY KEY (id)",
    "browser_sessions|ck_browser_sessions_idle_expiry|c|CHECK (idle_expires_at <= expires_at)",
    "browser_sessions|fk_browser_sessions_user|f|FOREIGN KEY (user_id) REFERENCES users(id)",
    "browser_sessions|fk_browser_sessions_user_identity|f|FOREIGN KEY (user_id, identity_id) REFERENCES external_identities(user_id, id)",
    "browser_sessions|pk_browser_sessions|p|PRIMARY KEY (id)",
    "browser_sessions|uq_browser_sessions_digest|u|UNIQUE (session_digest)",
    "commands|ck_commands_completion_pair|c|CHECK (response_status IS NULL AND completed_at IS NULL OR response_status >= 100 AND response_status <= 599 AND completed_at IS NOT NULL)",
    "commands|ck_commands_payload_digest|c|CHECK (char_length(payload_digest::text) = 64)",
    "commands|ck_commands_project_not_scope_sentinel|c|CHECK (project_id IS NULL OR project_id <> '00000000-0000-0000-0000-000000000000'::uuid)",
    "commands|fk_commands_organization|f|FOREIGN KEY (organization_id) REFERENCES organizations(id)",
    "commands|fk_commands_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "commands|pk_commands|p|PRIMARY KEY (id)",
    "commands|uq_commands_identity|u|UNIQUE (organization_id, actor_id, operation, idempotency_key)",
    "commands|uq_commands_organization_id|u|UNIQUE (organization_id, id)",
    "commands|uq_commands_project_id|u|UNIQUE (organization_id, project_id, id)",
    "commands|uq_commands_scope_id|u|UNIQUE (organization_id, scope_project_id, id)",
    "external_identities|ck_external_identities_version_positive|c|CHECK (version > 0)",
    "external_identities|fk_external_identities_user|f|FOREIGN KEY (user_id) REFERENCES users(id)",
    "external_identities|pk_external_identities|p|PRIMARY KEY (id)",
    "external_identities|uq_external_identities_issuer_subject|u|UNIQUE (issuer, subject)",
    "external_identities|uq_external_identities_user_id|u|UNIQUE (user_id, id)",
    "legacy_registrations|ck_legacy_registrations_digest|c|CHECK (char_length(manifest_digest::text) = 64)",
    "legacy_registrations|ck_legacy_registrations_schema_version_positive|c|CHECK (schema_version > 0)",
    "legacy_registrations|ck_legacy_registrations_status|c|CHECK (status::text = ANY (ARRAY['read_only'::character varying, 'imported'::character varying, 'tombstoned'::character varying]::text[]))",
    "legacy_registrations|fk_legacy_registrations_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "legacy_registrations|fk_legacy_registrations_registered_by|f|FOREIGN KEY (registered_by) REFERENCES users(id)",
    "legacy_registrations|pk_legacy_registrations|p|PRIMARY KEY (id)",
    "legacy_registrations|uq_legacy_registrations_project_locator|u|UNIQUE (project_id, opaque_locator)",
    "oidc_transactions|ck_oidc_transactions_return_path|c|CHECK (char_length(return_path) > 0)",
    "oidc_transactions|pk_oidc_transactions|p|PRIMARY KEY (id)",
    "oidc_transactions|uq_oidc_transactions_state_digest|u|UNIQUE (state_digest)",
    "organization_memberships|ck_organization_memberships_role|c|CHECK (role::text = 'organization_admin'::text)",
    "organization_memberships|ck_organization_memberships_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'revoked'::character varying]::text[]))",
    "organization_memberships|ck_organization_memberships_version_positive|c|CHECK (version > 0)",
    "organization_memberships|fk_organization_memberships_organization|f|FOREIGN KEY (organization_id) REFERENCES organizations(id)",
    "organization_memberships|fk_organization_memberships_user|f|FOREIGN KEY (user_id) REFERENCES users(id)",
    "organization_memberships|pk_organization_memberships|p|PRIMARY KEY (id)",
    "organization_memberships|uq_organization_memberships_organization_user|u|UNIQUE (organization_id, user_id)",
    "organizations|ck_organizations_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'disabled'::character varying, 'tombstoned'::character varying]::text[]))",
    "organizations|ck_organizations_version_positive|c|CHECK (version > 0)",
    "organizations|pk_organizations|p|PRIMARY KEY (id)",
    "organizations|uq_organizations_slug|u|UNIQUE (slug)",
    "outbox_events|ck_outbox_events_attempts_nonnegative|c|CHECK (publication_attempts >= 0)",
    "outbox_events|ck_outbox_events_schema_version_positive|c|CHECK (schema_version > 0)",
    "outbox_events|ck_outbox_events_sequence_positive|c|CHECK (aggregate_sequence > 0)",
    "outbox_events|fk_outbox_events_organization|f|FOREIGN KEY (organization_id) REFERENCES organizations(id)",
    "outbox_events|fk_outbox_events_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "outbox_events|pk_outbox_events|p|PRIMARY KEY (id)",
    "outbox_events|uq_outbox_events_aggregate_sequence|u|UNIQUE (aggregate_type, aggregate_id, aggregate_sequence)",
    "paper_versions|ck_paper_versions_revision_positive|c|CHECK (revision > 0)",
    "paper_versions|ck_paper_versions_sha256|c|CHECK (char_length(sha256::text) = 64)",
    "paper_versions|ck_paper_versions_size_nonnegative|c|CHECK (size_bytes >= 0)",
    "paper_versions|fk_paper_versions_created_by|f|FOREIGN KEY (created_by) REFERENCES users(id)",
    "paper_versions|fk_paper_versions_paper_tenant|f|FOREIGN KEY (organization_id, project_id, paper_id) REFERENCES papers(organization_id, project_id, id)",
    "paper_versions|pk_paper_versions|p|PRIMARY KEY (id)",
    "paper_versions|uq_paper_versions_paper_id|u|UNIQUE (organization_id, project_id, paper_id, id)",
    "paper_versions|uq_paper_versions_paper_revision|u|UNIQUE (paper_id, revision)",
    "paper_versions|uq_paper_versions_source_object|u|UNIQUE (source_object_id)",
    "paper_versions|uq_paper_versions_tenant_id|u|UNIQUE (organization_id, project_id, id)",
    "papers|ck_papers_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'tombstoned'::character varying]::text[]))",
    "papers|ck_papers_version_positive|c|CHECK (version > 0)",
    "papers|fk_papers_current_version_tenant_paper|f|FOREIGN KEY (organization_id, project_id, id, current_version_id) REFERENCES paper_versions(organization_id, project_id, paper_id, id)",
    "papers|fk_papers_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "papers|pk_papers|p|PRIMARY KEY (id)",
    "papers|uq_papers_project_digest|u|UNIQUE (project_id, content_sha256)",
    "papers|uq_papers_tenant_id|u|UNIQUE (organization_id, project_id, id)",
    "project_memberships|ck_project_memberships_role|c|CHECK (role::text = ANY (ARRAY['project_owner'::character varying, 'reviewer'::character varying, 'viewer'::character varying]::text[]))",
    "project_memberships|ck_project_memberships_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'revoked'::character varying]::text[]))",
    "project_memberships|ck_project_memberships_version_positive|c|CHECK (version > 0)",
    "project_memberships|fk_project_memberships_project_tenant|f|FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id)",
    "project_memberships|fk_project_memberships_user|f|FOREIGN KEY (user_id) REFERENCES users(id)",
    "project_memberships|pk_project_memberships|p|PRIMARY KEY (id)",
    "project_memberships|uq_project_memberships_project_user|u|UNIQUE (project_id, user_id)",
    "projects|ck_projects_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'disabled'::character varying, 'tombstoned'::character varying]::text[]))",
    "projects|ck_projects_version_positive|c|CHECK (version > 0)",
    "projects|fk_projects_organization|f|FOREIGN KEY (organization_id) REFERENCES organizations(id)",
    "projects|pk_projects|p|PRIMARY KEY (id)",
    "projects|uq_projects_tenant_id|u|UNIQUE (organization_id, id)",
    "report_versions|ck_report_versions_digest|c|CHECK (char_length(content_sha256::text) = 64)",
    "report_versions|ck_report_versions_status|c|CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'superseded'::character varying]::text[]))",
    "report_versions|ck_report_versions_versions_positive|c|CHECK (revision > 0 AND schema_version > 0)",
    "report_versions|fk_report_versions_created_by|f|FOREIGN KEY (created_by) REFERENCES users(id)",
    "report_versions|fk_report_versions_job_tenant|f|FOREIGN KEY (organization_id, project_id, job_id) REFERENCES review_jobs(organization_id, project_id, id)",
    "report_versions|pk_report_versions|p|PRIMARY KEY (id)",
    "report_versions|uq_report_versions_job_revision|u|UNIQUE (job_id, revision)",
    "report_versions|uq_report_versions_tenant_id|u|UNIQUE (organization_id, project_id, job_id, id)",
    "review_attempts|ck_review_attempts_number_positive|c|CHECK (attempt_number > 0)",
    "review_attempts|ck_review_attempts_status|c|CHECK (status::text = ANY (ARRAY['queued'::character varying, 'running'::character varying, 'blocked'::character varying, 'cancelled'::character varying, 'failed'::character varying, 'completed'::character varying]::text[]))",
    "review_attempts|fk_review_attempts_job_tenant|f|FOREIGN KEY (organization_id, project_id, job_id) REFERENCES review_jobs(organization_id, project_id, id)",
    "review_attempts|pk_review_attempts|p|PRIMARY KEY (id)",
    "review_attempts|uq_review_attempts_job_number|u|UNIQUE (job_id, attempt_number)",
    "review_attempts|uq_review_attempts_tenant_id|u|UNIQUE (organization_id, project_id, job_id, id)",
    "review_events|ck_review_events_schema_version_positive|c|CHECK (schema_version > 0)",
    "review_events|ck_review_events_sequence_positive|c|CHECK (aggregate_sequence > 0)",
    "review_events|fk_review_events_job_tenant|f|FOREIGN KEY (organization_id, project_id, job_id) REFERENCES review_jobs(organization_id, project_id, id)",
    "review_events|pk_review_events|p|PRIMARY KEY (id)",
    "review_events|uq_review_events_job_sequence|u|UNIQUE (job_id, aggregate_sequence)",
    "review_jobs|ck_review_jobs_attempt_nonnegative|c|CHECK (attempt >= 0)",
    "review_jobs|ck_review_jobs_mode|c|CHECK (mode::text = ANY (ARRAY['fast'::character varying, 'full'::character varying]::text[]))",
    "review_jobs|ck_review_jobs_stage|c|CHECK (stage::text = ANY (ARRAY['queued'::character varying, 'prepare'::character varying, 'parse'::character varying, 'positioning'::character varying, 'citation_audit'::character varying, 'execution'::character varying, 'review'::character varying, 'report'::character varying, 'finalize'::character varying, 'completed'::character varying]::text[]))",
    "review_jobs|ck_review_jobs_status|c|CHECK (status::text = ANY (ARRAY['queued'::character varying, 'running'::character varying, 'blocked'::character varying, 'cancelling'::character varying, 'cancelled'::character varying, 'failed'::character varying, 'completed'::character varying]::text[]))",
    "review_jobs|ck_review_jobs_version_positive|c|CHECK (version > 0)",
    "review_jobs|fk_review_jobs_created_by|f|FOREIGN KEY (created_by) REFERENCES users(id)",
    "review_jobs|fk_review_jobs_paper_version_tenant|f|FOREIGN KEY (organization_id, project_id, paper_version_id) REFERENCES paper_versions(organization_id, project_id, id)",
    "review_jobs|pk_review_jobs|p|PRIMARY KEY (id)",
    "review_jobs|uq_review_jobs_tenant_id|u|UNIQUE (organization_id, project_id, id)",
    "schema_metadata|pk_schema_metadata|p|PRIMARY KEY (key)",
    "stage_manifests|ck_stage_manifests_status|c|CHECK (status::text = ANY (ARRAY['pending'::character varying, 'committed'::character varying, 'superseded'::character varying]::text[]))",
    "stage_manifests|ck_stage_manifests_versions|c|CHECK (input_revision >= 0 AND output_revision > 0 AND schema_version > 0)",
    "stage_manifests|fk_stage_manifests_attempt_tenant|f|FOREIGN KEY (organization_id, project_id, job_id, attempt_id) REFERENCES review_attempts(organization_id, project_id, job_id, id)",
    "stage_manifests|pk_stage_manifests|p|PRIMARY KEY (id)",
    "stage_manifests|uq_stage_manifests_commit|u|UNIQUE (job_id, attempt_id, stage, input_revision)",
    "stage_manifests|uq_stage_manifests_tenant_id|u|UNIQUE (organization_id, project_id, job_id, id)",
    "users|ck_users_status|c|CHECK (status::text = ANY (ARRAY['active'::character varying, 'disabled'::character varying]::text[]))",
    "users|ck_users_version_positive|c|CHECK (version > 0)",
    "users|pk_users|p|PRIMARY KEY (id)",
    "work_items|ck_work_items_attempt_bounds|c|CHECK (attempt_count >= 0 AND max_attempts > 0 AND attempt_count <= max_attempts)",
    "work_items|ck_work_items_input_revision_nonnegative|c|CHECK (input_revision >= 0)",
    "work_items|ck_work_items_lease_pair|c|CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL))",
    "work_items|fk_work_items_attempt_tenant|f|FOREIGN KEY (organization_id, project_id, job_id, attempt_id) REFERENCES review_attempts(organization_id, project_id, job_id, id)",
    "work_items|fk_work_items_job_tenant|f|FOREIGN KEY (organization_id, project_id, job_id) REFERENCES review_jobs(organization_id, project_id, id)",
    "work_items|pk_work_items|p|PRIMARY KEY (id)",
    "work_items|uq_work_items_dedupe|u|UNIQUE (job_id, attempt_id, stage, input_revision)"
]),
        "indexes": tuple([
    "artifacts|ix_artifacts_tenant_job|CREATE INDEX ix_artifacts_tenant_job ON artifacts USING btree (organization_id, project_id, job_id)",
    "artifacts|pk_artifacts|CREATE UNIQUE INDEX pk_artifacts ON artifacts USING btree (id)",
    "artifacts|uq_artifacts_job_logical_name|CREATE UNIQUE INDEX uq_artifacts_job_logical_name ON artifacts USING btree (job_id, logical_name)",
    "artifacts|uq_artifacts_object_id|CREATE UNIQUE INDEX uq_artifacts_object_id ON artifacts USING btree (object_id)",
    "audit_events|ix_audit_events_command|CREATE INDEX ix_audit_events_command ON audit_events USING btree (organization_id, project_id, command_id)",
    "audit_events|ix_audit_events_tenant_created|CREATE INDEX ix_audit_events_tenant_created ON audit_events USING btree (organization_id, project_id, created_at, id)",
    "audit_events|pk_audit_events|CREATE UNIQUE INDEX pk_audit_events ON audit_events USING btree (id)",
    "browser_sessions|ix_browser_sessions_expiry|CREATE INDEX ix_browser_sessions_expiry ON browser_sessions USING btree (expires_at, revoked_at)",
    "browser_sessions|pk_browser_sessions|CREATE UNIQUE INDEX pk_browser_sessions ON browser_sessions USING btree (id)",
    "browser_sessions|uq_browser_sessions_digest|CREATE UNIQUE INDEX uq_browser_sessions_digest ON browser_sessions USING btree (session_digest)",
    "commands|pk_commands|CREATE UNIQUE INDEX pk_commands ON commands USING btree (id)",
    "commands|uq_commands_identity|CREATE UNIQUE INDEX uq_commands_identity ON commands USING btree (organization_id, actor_id, operation, idempotency_key)",
    "commands|uq_commands_organization_id|CREATE UNIQUE INDEX uq_commands_organization_id ON commands USING btree (organization_id, id)",
    "commands|uq_commands_project_id|CREATE UNIQUE INDEX uq_commands_project_id ON commands USING btree (organization_id, project_id, id)",
    "commands|uq_commands_scope_id|CREATE UNIQUE INDEX uq_commands_scope_id ON commands USING btree (organization_id, scope_project_id, id)",
    "external_identities|pk_external_identities|CREATE UNIQUE INDEX pk_external_identities ON external_identities USING btree (id)",
    "external_identities|uq_external_identities_issuer_subject|CREATE UNIQUE INDEX uq_external_identities_issuer_subject ON external_identities USING btree (issuer, subject)",
    "external_identities|uq_external_identities_user_id|CREATE UNIQUE INDEX uq_external_identities_user_id ON external_identities USING btree (user_id, id)",
    "legacy_registrations|pk_legacy_registrations|CREATE UNIQUE INDEX pk_legacy_registrations ON legacy_registrations USING btree (id)",
    "legacy_registrations|uq_legacy_registrations_project_locator|CREATE UNIQUE INDEX uq_legacy_registrations_project_locator ON legacy_registrations USING btree (project_id, opaque_locator)",
    "oidc_transactions|ix_oidc_transactions_expiry|CREATE INDEX ix_oidc_transactions_expiry ON oidc_transactions USING btree (expires_at)",
    "oidc_transactions|pk_oidc_transactions|CREATE UNIQUE INDEX pk_oidc_transactions ON oidc_transactions USING btree (id)",
    "oidc_transactions|uq_oidc_transactions_state_digest|CREATE UNIQUE INDEX uq_oidc_transactions_state_digest ON oidc_transactions USING btree (state_digest)",
    "organization_memberships|pk_organization_memberships|CREATE UNIQUE INDEX pk_organization_memberships ON organization_memberships USING btree (id)",
    "organization_memberships|uq_organization_memberships_organization_user|CREATE UNIQUE INDEX uq_organization_memberships_organization_user ON organization_memberships USING btree (organization_id, user_id)",
    "organizations|pk_organizations|CREATE UNIQUE INDEX pk_organizations ON organizations USING btree (id)",
    "organizations|uq_organizations_slug|CREATE UNIQUE INDEX uq_organizations_slug ON organizations USING btree (slug)",
    "outbox_events|ix_outbox_events_unpublished|CREATE INDEX ix_outbox_events_unpublished ON outbox_events USING btree (published_at, created_at)",
    "outbox_events|pk_outbox_events|CREATE UNIQUE INDEX pk_outbox_events ON outbox_events USING btree (id)",
    "outbox_events|uq_outbox_events_aggregate_sequence|CREATE UNIQUE INDEX uq_outbox_events_aggregate_sequence ON outbox_events USING btree (aggregate_type, aggregate_id, aggregate_sequence)",
    "paper_versions|pk_paper_versions|CREATE UNIQUE INDEX pk_paper_versions ON paper_versions USING btree (id)",
    "paper_versions|uq_paper_versions_paper_id|CREATE UNIQUE INDEX uq_paper_versions_paper_id ON paper_versions USING btree (organization_id, project_id, paper_id, id)",
    "paper_versions|uq_paper_versions_paper_revision|CREATE UNIQUE INDEX uq_paper_versions_paper_revision ON paper_versions USING btree (paper_id, revision)",
    "paper_versions|uq_paper_versions_source_object|CREATE UNIQUE INDEX uq_paper_versions_source_object ON paper_versions USING btree (source_object_id)",
    "paper_versions|uq_paper_versions_tenant_id|CREATE UNIQUE INDEX uq_paper_versions_tenant_id ON paper_versions USING btree (organization_id, project_id, id)",
    "papers|ix_papers_tenant_project|CREATE INDEX ix_papers_tenant_project ON papers USING btree (organization_id, project_id)",
    "papers|pk_papers|CREATE UNIQUE INDEX pk_papers ON papers USING btree (id)",
    "papers|uq_papers_project_digest|CREATE UNIQUE INDEX uq_papers_project_digest ON papers USING btree (project_id, content_sha256)",
    "papers|uq_papers_tenant_id|CREATE UNIQUE INDEX uq_papers_tenant_id ON papers USING btree (organization_id, project_id, id)",
    "project_memberships|ix_project_memberships_tenant_user|CREATE INDEX ix_project_memberships_tenant_user ON project_memberships USING btree (organization_id, user_id)",
    "project_memberships|pk_project_memberships|CREATE UNIQUE INDEX pk_project_memberships ON project_memberships USING btree (id)",
    "project_memberships|uq_project_memberships_project_user|CREATE UNIQUE INDEX uq_project_memberships_project_user ON project_memberships USING btree (project_id, user_id)",
    "projects|ix_projects_organization|CREATE INDEX ix_projects_organization ON projects USING btree (organization_id)",
    "projects|pk_projects|CREATE UNIQUE INDEX pk_projects ON projects USING btree (id)",
    "projects|uq_projects_tenant_id|CREATE UNIQUE INDEX uq_projects_tenant_id ON projects USING btree (organization_id, id)",
    "report_versions|pk_report_versions|CREATE UNIQUE INDEX pk_report_versions ON report_versions USING btree (id)",
    "report_versions|uq_report_versions_job_revision|CREATE UNIQUE INDEX uq_report_versions_job_revision ON report_versions USING btree (job_id, revision)",
    "report_versions|uq_report_versions_tenant_id|CREATE UNIQUE INDEX uq_report_versions_tenant_id ON report_versions USING btree (organization_id, project_id, job_id, id)",
    "review_attempts|pk_review_attempts|CREATE UNIQUE INDEX pk_review_attempts ON review_attempts USING btree (id)",
    "review_attempts|uq_review_attempts_job_number|CREATE UNIQUE INDEX uq_review_attempts_job_number ON review_attempts USING btree (job_id, attempt_number)",
    "review_attempts|uq_review_attempts_tenant_id|CREATE UNIQUE INDEX uq_review_attempts_tenant_id ON review_attempts USING btree (organization_id, project_id, job_id, id)",
    "review_events|ix_review_events_tenant_cursor|CREATE INDEX ix_review_events_tenant_cursor ON review_events USING btree (organization_id, project_id, created_at, id)",
    "review_events|pk_review_events|CREATE UNIQUE INDEX pk_review_events ON review_events USING btree (id)",
    "review_events|uq_review_events_job_sequence|CREATE UNIQUE INDEX uq_review_events_job_sequence ON review_events USING btree (job_id, aggregate_sequence)",
    "review_jobs|ix_review_jobs_tenant_status|CREATE INDEX ix_review_jobs_tenant_status ON review_jobs USING btree (organization_id, project_id, status)",
    "review_jobs|pk_review_jobs|CREATE UNIQUE INDEX pk_review_jobs ON review_jobs USING btree (id)",
    "review_jobs|uq_review_jobs_tenant_id|CREATE UNIQUE INDEX uq_review_jobs_tenant_id ON review_jobs USING btree (organization_id, project_id, id)",
    "schema_metadata|pk_schema_metadata|CREATE UNIQUE INDEX pk_schema_metadata ON schema_metadata USING btree (key)",
    "stage_manifests|pk_stage_manifests|CREATE UNIQUE INDEX pk_stage_manifests ON stage_manifests USING btree (id)",
    "stage_manifests|uq_stage_manifests_commit|CREATE UNIQUE INDEX uq_stage_manifests_commit ON stage_manifests USING btree (job_id, attempt_id, stage, input_revision)",
    "stage_manifests|uq_stage_manifests_tenant_id|CREATE UNIQUE INDEX uq_stage_manifests_tenant_id ON stage_manifests USING btree (organization_id, project_id, job_id, id)",
    "users|pk_users|CREATE UNIQUE INDEX pk_users ON users USING btree (id)",
    "work_items|ix_work_items_claim|CREATE INDEX ix_work_items_claim ON work_items USING btree (available_at, lease_expires_at, dead_lettered_at)",
    "work_items|pk_work_items|CREATE UNIQUE INDEX pk_work_items ON work_items USING btree (id)",
    "work_items|uq_work_items_dedupe|CREATE UNIQUE INDEX uq_work_items_dedupe ON work_items USING btree (job_id, attempt_id, stage, input_revision)"
]),
        "triggers": tuple([
    "audit_events|trg_audit_events_append_only|CREATE TRIGGER trg_audit_events_append_only BEFORE DELETE OR UPDATE ON audit_events FOR EACH ROW EXECUTE FUNCTION peerassist_reject_audit_mutation()"
]),
    }
)

OWNED_TABLES = tuple(entry.split("|", 1)[0] for entry in EXPECTED_CATALOG_SIGNATURE["tables"])


def catalog_signature_from_row(row: Mapping[str, Any]) -> dict[str, tuple[str, ...]]:
    return {key: tuple(row[key] or ()) for key in _SIGNATURE_KEYS}


def catalog_fingerprint(signature: Mapping[str, Sequence[str]]) -> str:
    payload = {key: list(signature[key]) for key in _SIGNATURE_KEYS}
    serialized = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    return hashlib.sha256(serialized).hexdigest()


EXPECTED_CATALOG_FINGERPRINT = catalog_fingerprint(EXPECTED_CATALOG_SIGNATURE)
