parent=base
import=common/keycloak
styles=css/login.css
cacheThemes=false
cacheTemplates=false
kcFormGroupClass=pf-v5-c-form__group
kcLabelWrapperClass=pf-v5-c-form__label-wrap
kcLabelClass=pf-v5-c-form__label
kcInputWrapperClass=pf-v5-c-form__input-wrap
kcInputClass=pf-v5-c-form-control
kcInputHelperTextBeforeClass=pf-v5-c-form__helper-text
kcInputHelperTextAfterClass=pf-v5-c-form__helper-text
kcInputErrorMessageClass=pf-v5-c-form__helper-text pf-m-error
kcContentWrapperClass=pf-v5-c-form__section
